version: '3'

services: 
  app: 
    build: .
    command: 'npm run start:dev'
    ports: 
      - '3001:3001'
    volumes: 
      - .:/usr/app
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=localhost
      - DB_PORT=3306

  db:
    container_name: 'db'
    image: mysql:8.0.23
    # command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    # command: CREATE DATABASE  IF NOT EXISTS `TRYBE_FUTEBOL_CLUBE`
    restart: always
    ports: 
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE='doctor'
    command: 